version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: groceries_frontend:1
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      REACT_APP_API_URL: https://api.groceriesh.com/vendor

volumes:
  groceries:
